### ISSUE TITLE
User > Badge: Handle badge of users according if it has been already used

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1064]
**Badge Delete**
- [x] You cannot delete a badge that has already been used but you can deactivate it.
- [x] In the case, the badge list must be retrieved with the number of sessions which can also be displayed in a new column named 'Nbr of Sessions'.
- [x] When the number of session > 0, the delete button is disabled (check to be done also in the backend).

**Badge Activate/Deactivate**
- [x] Deactivate/Activate row action per badge row is a new feature in the UI in addition to the Delete per badge always active.
- [x] When the badge is active, only the Delete and Deactivate button are visible
- [x] When Deactivate clicked, a confirmation dialog explaining that the badge will be deactivated and cannot be used anymore to start a session.
- [x] If the user validates the dialog, the badge is marked Inactive meaning a new column in the UI named Status has to be added with value 'Active' or 'Inactive' with a Badge control like User Status.
- [x] When the user clicks on Save, a call is done in the backend and badges are saved with a new prop named 'inactive' set to true in the tags collection. Delete/Update of badges have to be checked in the backend also.
- [x] When deactivated, the button Deactivate in then no longer visible and a new one appears named Activate.
- [x] The Admin can reactivate them again and Save.

**Backend**
- [x] If the badge is inactive, the authorization during a start transaction is rejected and the error message is logged in the backend.
- [x] When you have an orphan badge in the DB, it should be deleted (migration task to clean up). This should never happen. Nevertheless, the use case should be handled properly with a comprehensive error message in the backend

**User Delete**
- [x] If the user has no session, user and its badges are deleted from the DB.
- [x] If the user has at least one session, it has to be logically deleted with its props anonymized as done today and the badges with at least one session have to be deactivated, the others are deleted.
- [x] All the rules above have to be enforced in the backend.

**Unit Tests**
- [ ] Provide unit tests for all the cases above (you can work with Mehdi for that part)

**Comment by fcoutellier** [comment]
@mahdibenromdhane : Could you please take care of this ASAP? Thanks in advance.
 

- [ ] Provide unit tests for all the cases above (you can work with Mehdi for that part)

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane : Could you please take care of this ASAP? Thanks in advance.
> 
> * [ ]  Provide unit tests for all the cases above (you can work with Mehdi for that part)

Okey

**Comment by mariansalceda** [comment]
@fcoutellier pending, failed locally when testing.  @mahdibenromdhane  will have a look later
