### ISSUE TITLE
Charging Profile - Issue with Add scenario

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1218]
Clicking ADD button must set the Date field with the date of the day instead of taking the existing date.
The current issue is that by clicking on the ADD button the End User has no change to avoid an error.

![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/eb52e2af-91d4-4f3d-8a16-628a73a24724)

**Comment by LucasBrazi06** [comment]
@fcoutellier double check if this is still relevant. Thanks.
