### ISSUE TITLE
Asset Management - Delete issue

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1288]
Delete building return inconsistent message
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/4de5d778-7da5-4d09-ac8e-980c38aa20e3)

**Comment by fcoutellier** [comment]
Chrome cache cleared and tested again on QA test charger tenant same issue occurs again.

![image](https://user-images.githubusercontent.com/7858535/81916996-e6711f00-95d4-11ea-8147-68c76acee23a.png)

**Comment by LucasBrazi06** [comment]
Provided a fix on SocketIO.
Just tested it in QA and no errors in the logs anymore:
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/bbf10bb4-9caf-4e91-85d1-2f22ad940b3c)
I hope, this will work for good this time :S !
