### ISSUE TITLE
Charging Station > OCPP Params: Add a free key/value input field in OCPP Param

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1296]
The goal is to be able to enter a free key and sets its value.
Cahors chargers has hidden keys.

**Comment by fcoutellier** [comment]
Should be fixed today (20 May)

**Comment by fcoutellier** [comment]
@WillyLellouch : Could you please fix this?
![image](https://user-images.githubusercontent.com/7858535/88041819-3deab880-cb4b-11ea-999f-327d892898fa.png)

**Comment by WillyLellouch** [comment]
@fcoutellier I'm looking at it asap
