### ISSUE TITLE
Billing - Sync issue error log inconsistent

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1305]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/ea1afa0c-5043-4034-85c2-d882d1ecca9e)

Tenant: https://demobilling.qa-evse.cfapps.eu10.hana.ondemand.com/logs
### How-To
1) Remove the private key & sync
2) Enter a proper private key & sync

Issue occurs

**Comment by LucasBrazi06** [comment]
Ok
