### ISSUE TITLE
QA on Schneider Charging Station - Time zone ( summer - winter)

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1385]
Need to check if the time zone has properly been updated from winter to summer time automatically

**Comment by jerome-benoit** [comment]
The configuration template for Schneider Charging Station set the timezone to UTC, which means there's no summer/winter time change. I do not know the history and rationale behind that setup, so I've not made any changes in the template.

**Comment by LucasBrazi06** [comment]
Double check with @fcoutellier and close the issue eventually. Thanks!

**Comment by jerome-benoit** [comment]
I can change the timezone in the template but I would prefer to not add the timezone in the template because we already have Schneider chargers in different timezones. 
I think we can handle the timezone setting automatically by using the charger coordinates on a per vendor basis during templates application.

**Comment by LucasBrazi06** [comment]
> I can change the timezone in the template but I would prefer to not add the timezone in the template because we already have Schneider chargers in different timezones.
> I think we can handle the timezone setting automatically by using the charger coordinates on a per vendor basis during templates application.

This is what we do when we start a session, authorize (Utils.getTimezone(chargingStation.coordinates)

**Comment by jerome-benoit** [comment]
> > I think we can handle the timezone setting automatically by using the charger coordinates on a per vendor basis during templates application.
> 
> This is what we do when we start a session, authorize (Utils.getTimezone(chargingStation.coordinates)

So there's no point on setting the timezone in the template then, I will remove it and let charger admin a manual timezone setup.

**Comment by LucasBrazi06** [comment]
Ok

**Comment by LucasBrazi06** [comment]
Can be checked in OCPP parameter

**Comment by jerome-benoit** [comment]
> Can be checked in OCPP parameter

- Remove the timezone setting in the configuration template;
- Set proper location on all chargers in all production tenants;
- Set proper timezone on all chargers in all production tenants.
