### ISSUE TITLE
Car Management - Basic/Admin Role

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1403]
**Edit/Create pop-up**
- [x] Create Car for Basic & Admin
- [x] [Basic] In case of if the car exists (same VIN + PlateID), propose to reuse it for Basic users only
- [x] Set default user's car (check box)
- [x] Provide radio button for Company and Private car
- [x] [Admin] New tab named Users to assign one or several cars to a user and set default/private/company car
- [x] When enter key is hit, same behavior as if user clicked on Save with the same constraints

**Car list**
- [x] Display the user column in the list
- [x] Add User filter for Admin
- [X] Edit Car (VIN, etc)
- [x] Delete Car (check if there is existing transaction -> If this is the case, logical delete)

- [x] Car must have a unique index on VIN & matriculation
- [x] Check and provide text IDs to translate in ES & DE for cars

**Comment by mahdibenromdhane** [comment]
This PR handles:
Basic User:
- Set default user's car
- Set Private/Company attribute

**Comment by fcoutellier** [comment]
PR planned today 20-May

**Comment by LucasBrazi06** [comment]
When creating a car, I forgot to mention that we have to choose also the type of converter in a drop-down.
230V32A3X	32 A	3 phases	    7 kW
...
Check also the advanced tab, it seems not working anymore.
Thanks!
