### ISSUE TITLE
SmartCharging - Auto Refresh Charge plan when smartcharge update it result.

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1413]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/c5d9717a-024c-4c9f-b499-ed3e09af8220)

**Comment by jerome-benoit** [comment]
Related issue with documentation: https://github.com/LucasBrazi06/ev-dashboard/issues/1602

**Comment by LucasBrazi06** [comment]
Implemented it in commit 81376f81c61e29d74d01c1aadca2636834694b46

**Comment by jerome-benoit** [comment]
> Implemented it in commit [81376f8](https://github.com/LucasBrazi06/ev-dashboard/commit/81376f81c61e29d74d01c1aadca2636834694b46)

You should guard the subscription to the subject by a check on `this.configService.getCentralSystemServer().socketIOEnabled `

**Comment by LucasBrazi06** [comment]
> socketIOEnabled

Done, thanks!
