### ISSUE TITLE
Charging Station > OCPP Parameters > Regression: Put back two missing features

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1437]
Following the refactoring of the list in the OCPP Parameters tab, we lost two features:
- [x] Apply OCPP Params in Template
- [x] Request OCPP Params
Put them back!

**Comment by fcoutellier** [comment]
@OliveGerste Hi Tobias, Could you please cross review this issue please?

**Comment by OliveGerste** [comment]
@fcoutellier Hi Fred, is there a PR regarding this issue or what exactly needs to be reviewed?

**Comment by fcoutellier** [comment]
@WillyLellouch: Please see directly with Tobias what you need to reviewed from your side.

Best regards,
Fred

**Comment by WillyLellouch** [comment]
@OliveGerste 
https://github.com/LucasBrazi06/ev-dashboard/tree/bugfix-regression-ocpp-params-missing-features
This is the branch that has the two missing features.
I need their functionalities reviewed.
They are situated in the ocpp parameters section of a charger
Thanks

**Comment by OliveGerste** [comment]
@WillyLellouch 
Hi Willy, could you provide a PR so that I can add my feedback?

**Comment by fcoutellier** [comment]
@WillyLellouch Hi Willy, please provide a PR as requested by Tobias. It will be more convenient to make comments.

If necessary, call each other.

Thanks,

**Comment by jerome-benoit** [comment]
I still think that having a 'save all' button to save several changes made to OCPP parameters would be handy. 

Otherwise, the two other features are back.

**Comment by LucasBrazi06** [comment]
> I still think that having a 'save all' button to save several changes made to OCPP parameters would be handy.

When OCPP will support it we'll do :-)
