### ISSUE TITLE
Smart Charging - Add a select button to switch from kW to Amps in the charging AND Site curve (Session and Charging Plan)

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1464]
- [x] Charging Curve
- [x] Site Curve
- [x] Charging Plans

![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/18f5b46b-0057-4081-87d6-c0b7a995f20b)

**Comment by OliveGerste** [comment]
@LucasBrazi06 
Hi Serge,
The limit in Amps is currently stored per phase, which results in a higher instant Amp (all phases) value than the limit in the curve:
![Uploading image.png…]()
Do you have a suggestion how to handle this right now?

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06
> Hi Serge,
> The limit in Amps is currently stored per phase, which results in a higher instant Amp value (all phases) than the limit in the curve:
> ![image](https://user-images.githubusercontent.com/33114317/82420287-d26b6880-9a7f-11ea-91cb-34767ebb2b07.png)
> 
> Do you have a suggestion how to handle this at the moment?

Change the limitAmp to contain the total of the 3 phases (in meter value + migration task).
I'm changing the template to that direction also, to get the total amps of the connector and no longer the amp per phase.

**Comment by mahdibenromdhane** [comment]
![image](https://user-images.githubusercontent.com/33232018/83136336-91aac980-a0e7-11ea-9e9e-83a52ddaf63f.png)
Hello, 
Everything seems to be fine except that the spinner does not show in the graphs of the transactions
