### ISSUE TITLE
Calendar filtering problem

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1521]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/2216ccce-609b-496d-9931-78b266785d6e)

**Comment by OliveGerste** [comment]
Issue is solved by the implementation of the new date picker on the statistics pages. (Tested)
Not yet implemented for the other pages in the app. e.g. logs:
![image](https://user-images.githubusercontent.com/33114317/93781570-cc51e800-fc29-11ea-83c2-b2c1e6b2947d.png)

**Comment by LucasBrazi06** [comment]
@OliveGerste 
Perfect, thanks!
I'll close the issue.
