### ISSUE TITLE
Setting > Analitycs

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1578]
Missing check and button
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/07f214d6-ce63-49f6-9b99-d81ec7559a24)

**Comment by LucasBrazi06** [comment]
Fyi, there is no save button, it is saved with the Settings' Save one.

**Comment by Namachi06** [comment]
As this issue has been already resolved, I close it.
