### ISSUE TITLE
 Charging Station > List of Charging Plans (New tab before "In Error" tab)

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1585]
List of Charging Plans (New tab before "In Error" tab)
**Columns**
- [ ] Charging station ID
- [ ] Connector ID
- [ ] Kind of Plan, Purpose and Stack level
- [ ] Site area name (if component Organization is active)
- [ ] Current site area limitation (W/A)

**Comment by LucasBrazi06** [comment]
@fcoutellier this issue should be an epic as discussed: bunch of checkboxes should be limited as a feature that can be tested to moved in QA once done.

**Comment by LucasBrazi06** [comment]
@fcoutellier 
Could you move the checkboxes in an Epic and create an issue per dev and testable units?
Thanks

**Comment by LucasBrazi06** [comment]
@OliveGerste 
To be changed is the Site Admin role handling.
Check how it is done in charging stations.

**Comment by fcoutellier** [comment]
My bad, I do it now.
