### ISSUE TITLE
Charing Station > Simplification of Charging Station and Sessions list

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1586]
- [x] [will increase the height of the details which will cut the chart in small screen + all important info is already in the connectors' details] Display header in details like in the pop-up
- [x]  Remove the pop-up action [cannot be removed, show the last transaction on connector]
- [x]  Add the user in the connector and display it in the connector list (Admin and Site Admin only)
- [x]  Add switch button named Consumption: Amps/Watts in chart (change the legend accordingly)
- [x] [Dups of #626] Add switch button named Phases : Split / All (change the legend accordingly)

**Comment by LucasBrazi06** [comment]
We have also to keep the feature that display the last run session on connector when no session is in progress:
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/ceeeda5b-2c67-420c-b200-8c747581f054)
