### ISSUE TITLE
Mobile > Charging Station Parameter

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1594]
According to the tab order the Action screen must be displayed first instead of the properties.

![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/0092c6d8-95bb-46c2-8869-d8dfd35845bc)

**Comment by mariansalceda** [comment]
I think this was already done by Serge. 
![image](https://user-images.githubusercontent.com/49985704/82035295-9e6afe80-969f-11ea-84fb-03fee0dad792.png)

**Comment by LucasBrazi06** [comment]
Yes :)

**Comment by fcoutellier** [comment]
LOL ok to be tested then :)
