### ISSUE TITLE
Tenant Management

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1598]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/cefe0914-0e1c-4179-b6e7-6b7a6c0aa47a)

Investigate if some buttons can be added at the end of the list
- Create
- Cancel

**Comment by mariansalceda** [comment]
I found this documentation:
https://docs.nativebase.io/Components.html#actionsheet-def-headref

I don't think it's possible to add buttons to the actionSheet
