### ISSUE TITLE
Check Socket.IO is consumed by all the list in the front-end

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1602]
Identify views not consuming socket io.
Establish a list
Train the dev during team meeting so they will do it

**Comment by LucasBrazi06** [comment]
I found also these classes not listening to changes so far:
- CarCatalogsListTableDataSource (Mehdi - reported in an issue)
- CarsListTableDataSource
- ChargingStationChargingProfileLimitScheduleTableDataSource (Tobias - reported in an issue)

**Comment by jerome-benoit** [comment]
All the changes on collections are now pushed through socket.io to the dashboard. 
The next steps will probably be on how to use them on the dashboard to do the display refreshing on some lists.

**Comment by jerome-benoit** [comment]
Madhi's PR https://github.com/LucasBrazi06/ev-server/pull/1519 will add two new collections to monitor after the merge. 

Most of the list using the shared table code in the dashboard that does not have an auto refresh toggle button just need to: 

- add a `getDataChangeSubject()` method that will return the right `Observable` attributes from the `CentralServerNotificationService` module in their data source (already done)
- add `new TableAutoRefreshAction(false).getActionDef()` in the array returned by  the `buildTableActionsRightDef()` method in their data source

For refreshing the display of one record in the DB in case of db operations like update, delete, etc. on it, specific code is needed at the component level for now that can borrowed from the display of one transaction component. The target here is the display refresh of the charging profiles attached to a level (site, site area, etc.).

**Comment by LucasBrazi06** [comment]
Ok, I will check that and let you know.

**Comment by jerome-benoit** [comment]
- src/app/pages/assets/list/assets-list-table-data-source.ts: No auto refresh toggle button -> Liam
- src/app/pages/cars/car-catalogs/car-catalogs-list-table-data-source.ts: No auto refresh toggle button -> Madhi
- src/app/pages/cars/cars/cars-list-table-data-source.ts:  No auto refresh toggle button -> Madhi

**Comment by LucasBrazi06** [comment]
Added missing auto-refresh buttons in commit 579d0e7f8a2c508488e180d981a9d72df97efe5a

**Comment by LucasBrazi06** [comment]
If it was the last thing missing, you can close the issue.

**Comment by jerome-benoit** [comment]
> If it was the last thing missing, you can close the issue.

Liam will take care of the Assets list?

**Comment by LucasBrazi06** [comment]
> > If it was the last thing missing, you can close the issue.
> 
> Liam will take care of the Assets list?

If it was only the auto-refresh button missing, I added it everywhere.

**Comment by jerome-benoit** [comment]
> > > If it was the last thing missing, you can close the issue.
> > 
> > 
> > Liam will take care of the Assets list?
> 
> If it was only the auto-refresh button missing, I added it everywhere.

Indeed :) Need vacation. 

I close the issue.
