### ISSUE TITLE
Table initial column sorting not working any more

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-dashboard#1610]
I think it's related to the data source loading move in ngOnInit().

**Comment by LucasBrazi06** [comment]
I fixed it already ;)

**Comment by LucasBrazi06** [comment]
Putain tu l'as remis lol !
Je vais le remettre ggrrrr

**Comment by jerome-benoit** [comment]
> Putain tu l'as remis lol !
> Je vais le remettre ggrrrr
> 

Il faudrait le laisser dans ngOnInit(), c’est ici l’emplacement correct pour charger les data et fixer le pb de sorting a terme.

Je vais voir sur un simple setTimeout() règle pas les deux pbs en meme temps.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by LucasBrazi06** [comment]
> Putain tu l'as remis lol ! Je vais le remettre ggrrrr
> Il faudrait le laisser dans ngOnInit(), c’est ici l’emplacement correct pour charger les data et fixer le pb de sorting a terme. Je vais voir sur un simple setTimeout() règle pas les deux pbs en meme temps.
> […](#)
> -- Jérôme Benoit aka fraggle Piment Noir - https://piment-noir.org OpenPGP Key ID : 27B535D3 Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

Ok mais j'ai toujours l'erreur dans la console que tu as essayé de fixer.
Et dans le loadData, il faut verifier que l'on a pas de refs de type ViewChild qui ne sont dispos qu'apres le ngInit.

**Comment by jerome-benoit** [comment]
> > Il faudrait le laisser dans ngOnInit(), c’est ici l’emplacement correct pour charger les data et fixer le pb de sorting a terme. Je vais voir sur un simple setTimeout() règle pas les deux pbs en meme temps.

> Ok mais j'ai toujours l'erreur dans la console que tu as essayé de fixer.
> Et dans le loadData, il faut verifier que l'on a pas de refs de type ViewChild qui ne sont dispos qu'apres le ngInit.

Ouais, c'est le pb, je regarderais mais pas dans l'immédiat. Je laisse l'issue ouverte.
