### ISSUE TITLE
Charging Stations > Columns must all be center to avoid wide blank space on large screen

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1620]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/9de1f4ec-a2dd-4346-a948-886b12ee8630)

**Comment by LucasBrazi06** [comment]
This is not the kind of column to be centered imho.

**Comment by fcoutellier** [comment]
Gege request.

**Comment by LucasBrazi06** [comment]
> Gege request.

Je comprends, je la ferme alors hahahaha !
