### ISSUE TITLE
SCP dev landscape > Migrate to 4.2 Shared MongoDB Atlas

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-dashboard#1621]
ev-server now requires 4.2 MongoDB version to work.

**Comment by jerome-benoit** [comment]
Having a working dev landscape will be required soon.

**Comment by LucasBrazi06** [comment]
> Having a working dev landscape will be required soon.

Forget about MongoDB 4.2 instance in SCP, create a new dev instance 4.2 in Atlas and use it in SCP dev.
I think that version 4.4 is also already available...

**Comment by jerome-benoit** [comment]
> > Having a working dev landscape will be required soon.
> 
> Forget about MongoDB 4.2 instance in SCP, create a new dev instance 4.2 in Atlas and use it in SCP dev.
> I think that version 4.4 is also already available...

That's was the plan but no need for a dedicated cluster, too costly, shared cluster will be enough.

**Comment by jerome-benoit** [comment]
+ [ ] Current dev landscape DB imported on a MongoDB Atlas cluster; 
+ [ ] SAP-IT SCP dev landscape is not allowed to open connection to the outside world: the dev landscape will be moved to ou SCP account: 
  + [ ] Get the public IPs used on the SCP account;
  + [ ] Authorise them on cloud atlas.

That way, all spaces on the SCP account will be able to connect to cloud atlas.

**Comment by jerome-benoit** [comment]
Done.
