### ISSUE TITLE
Translation Spanish

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1630]
Could you please translate the i18N.properties files from English to Spanish?

Look for all of them in the git repositories.

Thanks,

**Comment by LucasBrazi06** [comment]
I close this issue as while we don't have the translation in the front-end, we cannot enable this language.
I created a new task for this integration #1645

**Comment by LucasBrazi06** [comment]
I keep it open for the Spanish translation in ev-dashboard and ev-server

**Comment by fcoutellier** [comment]
@mariansalceda Hi Marian, I compared your es.json file with the current en.json file and discovered several missing keys in the es.json.

Here is the list of missing key that I also added in the file enclosed:

   388: "smart_charging": "Smart Charging",
   
   413 : "max_limit_kw": "Limite Max",
   606: "user": "User",
   
    411 : "site_invalid": "Site Area invalid",
    
   1414:   "create_success": "Asset settings have been created successfully",
   1415:   "create_error": "Error occurred while creating the Asset settings",
   1416:  "update_success": "Asset settings have been updated successfully",
   1417:   "update_error": "Error occurred while updating the Asset settings"
   
   1816:   "amps": "Instant Grid Amps (A)",
   1818 : "energy_amps": "Energy Delivered (A.h)",
   1823 : "limit_plan_amps": "Plan Limit (A)",
   1824 : "limit": "Max Limit",
   1826 : "limit_amps": "Max Grid Limit (A)",
   
   1828 : "unit_kilowatts": "kW",
   1829 : "unit_amperage":  "Amp"
   
   1840 : "error": "An error occurred during the export of the sessions"
   
   
   
[missing_Translation_es.json.txt](https://github.com/LucasBrazi06/ev-dashboard/files/4730908/missing_Translation_es.json.txt)



Could you please translated the missing ones?

**Comment by fcoutellier** [comment]
@mariansalceda Please ensure to also create the Spanish entries to make the selection available on ev-server + ev-mobile (if not done already).

**Comment by jerome-benoit** [comment]
The EULA need also to be translated in spanish.

**Comment by LucasBrazi06** [comment]
Missing integration in the Dashboard

**Comment by LucasBrazi06** [comment]
@jerome-benoit 
Need to activate it in the Dashboard
Double check also DE
Notify Fred for testings

@fcoutellier 
Plan tests ES and DE on:
- [ ] Backend
- [ ] Front-end
- [ ] Mobile

**Comment by jerome-benoit** [comment]
> @jerome-benoit
> Need to activate it in the Dashboard

Done on QA.

> Double check also DE

There's no German translation. The translation needs to be done. Only the mobile app have one.

**Comment by fcoutellier** [comment]
@jerome-benoit Any chance to ave it today? It would be great for Marian to finalize the linguistic review. Thanks!

**Comment by jerome-benoit** [comment]
> @jerome-benoit Any chance to have it today? It would be great for Marian to finalize the linguistic review. Thanks!

Local enablement can be done by just adding the relevant configuration in the config files. 

For the QA landscape, you have to wait for the next deployment on QA that Derge will do.

**Comment by LucasBrazi06** [comment]
@fcoutellier Do you have the DE files from Marius?

**Comment by jerome-benoit** [comment]
The only missing part is the mobile app test and maybe translation corrections by @mariansalceda because of https://github.com/LucasBrazi06/ev-mobile/pull/200

**Comment by LucasBrazi06** [comment]
@fcoutellier double check the status to the test of the mobile translation.

**Comment by mariansalceda** [comment]
I finished testing the app, maybe someone else can test it in case i missed something

**Comment by jerome-benoit** [comment]
> I finished testing the app, maybe someone else can test it in case i missed something
> 
> The EULA doesn't get translated.

The mobile app have a bug on that respect, I will look at it and fix it.

**Comment by jerome-benoit** [comment]
@mariansalceda : Are you using Spanish on the QA landscape? If yes, we have an issue with the email notification. 

```
[
      {
            "error": "Unexpected token   in JSON at position 593",
            "stack": "SyntaxError: Unexpected token   in JSON at position 593
   at JSON.parse (<anonymous>)
   at EMailNotificationTask.prepareAndSendEmail (/home/vcap/app/dist/webpack:/src/notification/email/EMailNotificationTask.ts:235:34)
   at EMailNotificationTask.sendRequestPassword (/home/vcap/app/dist/webpack:/src/notification/email/EMailNotificationTask.ts:53:17)
   at Function.sendRequestPassword (/home/vcap/app/dist/webpack:/src/notification/NotificationHandler.ts:307:55)"
      }
]
```

**Comment by jerome-benoit** [comment]
> > I finished testing the app, maybe someone else can test it in case i missed something
> > The EULA doesn't get translated.
> 
> The mobile app have a bug on that respect, I will look at it and fix it.

Fixed in PR https://github.com/LucasBrazi06/ev-mobile/pull/201.

**Comment by mariansalceda** [comment]
@jerome-benoit  yes im using the spanish version everywhere. I do get the emails in spanish tho

**Comment by jerome-benoit** [comment]
> @jerome-benoit yes im using the spanish version everywhere. I do get the emails in spanish too

Ok, one spanish email translated json file have an issue then.

**Comment by mariansalceda** [comment]
So, now the eula (spanish version) only works on the app.

**Comment by jerome-benoit** [comment]
> So, now the eula (spanish version) only works on the app.

You mean that now the EULA stay in spanish after a locale change on Android?

**Comment by mariansalceda** [comment]
yes. it in Spanish only on the app. on the dashboard its still in English
![image.png](https://images.zenhubusercontent.com/5e5d2a5f0de74343d65e223a/43464076-8c55-42f4-ac26-14344ea5eb81)

**Comment by jerome-benoit** [comment]
I think it's a misconfiguration on your side.

**Comment by LucasBrazi06** [comment]
@jerome-benoit to enable DE, ES languages in prod when you'll have time.

**Comment by LucasBrazi06** [comment]
Dups of #1722
