### ISSUE TITLE
Make the sub-modules have only the master branch (remove master-qa)

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1635]

**Comment by jerome-benoit** [comment]
We already discussed that change before by mail and end up with a statu quo on that topic: we keep using only master-qa for submodule with typescript code and master for a future separation of production and qa code on that submodules if needed. What have changed since that motivated that issue?

**Comment by LucasBrazi06** [comment]
Either master/master-qa branch of repos like ev-server should point to the master/master-qa branch of the sub-modules if it's possible. If not ev-server points only to master and we remove the master-qa branch in sub-modules.

**Comment by jerome-benoit** [comment]
From what I've read in the git documentation, you can't have two different .gitmodules files in two different branches. Even with git 2.26 that offer improved support for split repository in submodules like ours. 
A git submodule always reference a commit id that can be the commit id of a tag, the latest commit id in a branch, etc. in the submodule repository. By default, git try to track the latest commit id in the master branch of the submodule repository.    
So you can make any branches in the main repo point to arbitrary commit id in submodules from whatever branches, tags, etc. in the sub repo but it's a manual process that can't by automated by a git configuration file, only with scripts or git alias. 

For example, I've added git alias to my local ev-server clone: 

```
[alias]
        sdiff = !git diff && git submodule foreach 'git diff'
        spush = push --recurse-submodules=on-demand
        supdate = submodule update --remote --merge
```

with 

```
$ git config alias.sdiff '!'"git diff && git submodule foreach 'git diff'"
$ git config alias.spush 'push --recurse-submodules=on-demand'
$ git config alias.supdate 'submodule update --remote --merge'   

```

The same can to done to checkout the same branch everywhere, the create the same tag everywhere, to commit sequentially changes to the main repo then on each submodule, etc. 
All desired operations in the codeflow can be automated somewhat with scripts or git alias, a good documentation is then needed on how to set them up and use it. The integration of special git commands is code is also possible but there's no plug and play solution.

**Comment by LucasBrazi06** [comment]
Ok, thanks for the explanation.
Then I still think we should get rid of master-qa branches in sub-module and reference only the master one.

**Comment by jerome-benoit** [comment]
> Ok, thanks for the explanation.
> Then I still think we should get rid of master-qa branches in sub-module and reference only the master one.

Let's do it then: 

+ PR to merge master-qa in master
+ PR to change .gitmodules and submodule commit id reference
+ Inform devs about it and that they will require to run `npm run git:supdate` 
+ Delete master-qa branch in repositories

**Comment by LucasBrazi06** [comment]
> > Ok, thanks for the explanation.
> > Then I still think we should get rid of master-qa branches in sub-module and reference only the master one.
> 
> Let's do it then:
> 
> * PR to merge master-qa in master
> * PR to change .gitmodules and submodule commit id reference
> * Inform devs about it and that they will require to run `npm run git:supdate`
> * Delete master-qa branch in repositories

Ok, I think only me can perform some of the tasks :)

**Comment by jerome-benoit** [comment]
I can make the PRs on master and change in ev-server but you will have to do the merge. But first you have to merge all PRs in standby on the submodules repositories.

**Comment by LucasBrazi06** [comment]
> I can make the PRs on master and change in ev-server but you will have to do the merge. But first you have to merge all PRs in standby on the submodules repositories.

Yep.

**Comment by LucasBrazi06** [comment]
Everything's done except the reference to the new sub-module commits in master.
