### ISSUE TITLE
Custom OCPP parameter and error handling

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1652]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/7d2f592f-bdaa-4413-82e3-eca841dc5cd0)

**Comment by WillyLellouch** [comment]
There is no error because the field itself limits the length. It's a function of how the field is validated (directly through html). Is it not OK this way ?

**Comment by fcoutellier** [comment]
As discussed, please forget about the OCPP id but kindly disable ASAP the "Save" Button when an error is detected.
