### ISSUE TITLE
Charging Station > Static Limitation cursor not modifiable when Smart Charging has been disabled

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1659]
The scenario is the following:
1) You have an ongoing charging session (Smart Charging enabled on the site-area)
2) You are on the charging plan screen
3) From another Chrome tab, go on the site-area screen and disable the Smart charging
4) Get back to other tab (charging station), the Plan is not editable after clicking on the refresh button
5) Switch to the Static Limitation tab

The cursor message Smart Charging is still displayed and you can't change the value

**Comment by LucasBrazi06** [comment]
I fixed it in commit 3beaad294c101cae377447838e2b1356db71fe5b
