### ISSUE TITLE
Charging Station Delta does not release the plug to unlock the cable

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1660]
Not sure if this is vendor related or an issue on or side...

**Comment by LucasBrazi06** [comment]
Double check with Gerald or Jerome if the auto-unlock when transaction is stopped is active.
We tested the unlock feature in the mobile app but the OCPP message was rejected by the Cahors charging station (this feature should be checked on a Schneider charger with auto-unlock set to false)
Until then, this is an issue to raise to the Cahors support (Damien)

**Comment by LucasBrazi06** [comment]
I just sent an email to Damien.

**Comment by jerome-benoit** [comment]
It's a systematic behaviour?

**Comment by jerome-benoit** [comment]
Version 3.3.2 deployed. Need to check if the issue is fixed.

**Comment by LucasBrazi06** [comment]
> Version 3.3.2 deployed. Need to check if the issue is fixed.

Move the issue in QA in that case, same for other issues.
Thanks!

**Comment by jerome-benoit** [comment]
Moved to asana.
