### ISSUE TITLE
User > Edit > Password : Implement a password generator button

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1670]
Implement a button to generate a new secure password compliant with the security rule.

**Comment by LucasBrazi06** [comment]
The user should enter his password, not a generated one which he will not recall.

**Comment by fcoutellier** [comment]
With the password manager, it is not an issue any longer. In addition, it could use the password recovery in case of need.

**Comment by LucasBrazi06** [comment]
> With the password manager, it is not an issue any longer. In addition, it could use the password recovery in case of need.

Ok, then the user can generate the new password in the password manager then, no ? ;-)

**Comment by fcoutellier** [comment]
Yes, it's true. It's your win ;-)
