### ISSUE TITLE
Munich Tenant Users onboarding - Import users in Munich's tenant

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1671]
[Copy of Mitarbeiter Liste_neu.xlsx](https://github.com/LucasBrazi06/ev-dashboard/files/4752156/Copy.of.Mitarbeiter.Liste_neu.xlsx)

**Comment by fcoutellier** [comment]
Email are missing we are waiting for a new Excel file.

**Comment by fcoutellier** [comment]
@mahdibenromdhane The Excel file in attachment already contains the e-mails. Please perform the import as soon as you have time.

Thanks,
Fred

**Comment by LucasBrazi06** [comment]
Tested by Philip in Munich
