### ISSUE TITLE
Dashboard: User got logged out with several same error messages appearing at once

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1677]
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/623fa3e4-fc1d-48d2-b50d-598bbba15e13)

**Comment by jerome-benoit** [comment]
The production landscape expose some instabilities that does not belong to our applications: none of the other landscape have similar issues. The underlying infrastructure need to be checked with SAP-IT people: ticket created.

**Comment by LucasBrazi06** [comment]
@fcoutellier I fixed message flooding + avoid force logout when SCP is not responding.
Now you should have one error displayed and you should be able to perform an action to refresh the list without refreshing all the browser.
Let me know if you can reproduce.

**Comment by fcoutellier** [comment]
@LucasBrazi06 I tested a while without getting this problem again. I close this issue and will reopen it in case of need. Thanks!

**Comment by LucasBrazi06** [comment]
Do not send the buffered MongoDB notifications if the connection is interrupted
