### ISSUE TITLE
Charging station settings can be not saved: Infinite mutual recursion call

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-dashboard#1685]
When a new charging station is added that have no matching template and an admin try to set its parameters, at save:

`Utils.getChargingStationPower()` is calling `Utils.getChargingStationAmperage()` that is calling `Utils.getChargingStationPower()` that is calling `Utils.getChargingStationAmperage()` ... until the max recursion stack size is reached. 

The mutual recursion is missing the ending condition before the call of each static method

**Comment by LucasBrazi06** [comment]
Fixed

**Comment by jerome-benoit** [comment]
> Fixed

When a station is disconnected, we can't save its connectors settings?

**Comment by LucasBrazi06** [comment]
> When a station is disconnected, we can't save its connectors settings?

No, it should work.

**Comment by jerome-benoit** [comment]
> > When a station is disconnected, we can't save its connectors settings?
> 
> No, it should work.

Ok, then we have an issue: the connector settings is not saved on my shelly wallbox that is currently disconnected on the shellywallbox tenant.
