### ISSUE TITLE
Investigate HANNO-WB-03 issue on Session ID 134873214 (Jun 7, 2020, 1:27:51 PM)

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1686]
Seems that Meter Values are wrong:

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/fcb750d3-5790-49aa-920f-595d7d570f85)

**Comment by jerome-benoit** [comment]
The Webasto connection to the backend is very unstable, dunno why. The charger resend metervalues that have already been sent at each reconnection.

**Comment by LucasBrazi06** [comment]
> The Webasto connection to the backend is very unstable, dunno why. The charger resend metervalues that have already been sent at each reconnection.

The issue I see is that we don't have real charging curve just like if we didn't receive/store the meter values

**Comment by jerome-benoit** [comment]
> > The Webasto connection to the backend is very unstable, dunno why. The charger resend metervalues that have already been sent at each reconnection.
> 
> The issue I see is that we don't have real charging curve just like if we didn't receive/store the meter values

We don't store them because because we already have a _id collision on the metervalues sent: the charger keep sending them with the same UUID. But honestly, that charger is unusable at the time, it can't a keep a connection to the backend.

**Comment by jerome-benoit** [comment]
The very same pattern is keeping happening again and again (same UUID, same number, same everything) always ending by 

```
[
      {
            "stack": "Error: Web socket closed for Message ID '87662384' with content '[3,\"87662384\",{}]' ([object Promise])
   at rejectCallback (/home/vcap/app/dist/webpack:/src/server/ocpp/json/WSConnection.ts:296:62)
   at /home/vcap/app/dist/webpack:/src/server/ocpp/json/WSConnection.ts:331:16
   at Promise._execute (/home/vcap/deps/0/node_modules/bluebird/js/release/debuggability.js:384:9)
   at Promise._resolveFromExecutor (/home/vcap/deps/0/node_modules/bluebird/js/release/promise.js:518:18)
   at new Promise (/home/vcap/deps/0/node_modules/bluebird/js/release/promise.js:103:10)
   at JsonWSConnection.sendMessage (/home/vcap/app/dist/webpack:/src/server/ocpp/json/WSConnection.ts:285:18)
   at JsonWSConnection.handleRequest (/home/vcap/app/dist/webpack:/src/server/ocpp/json/JsonWSConnection.ts:116:18)
   at JsonWSConnection.onMessage (/home/vcap/app/dist/webpack:/src/server/ocpp/json/WSConnection.ts:144:11)"
      }
] 
```

And the station stay deconnected for more than 180s. 

I will have to learn on how to factory reset that charger and do it on site.

**Comment by jerome-benoit** [comment]
Solved.  

The charger did not manage to properly finish a charging session and was sending over and over the same meter values. No logs on that vendor firmware so the root cause is unknown: no detection of the unlock on the car?

**Comment by LucasBrazi06** [comment]
> Solved.
> 
> The charger did not manage to properly finish a charging session and was sending over and over the same meter values. No logs on that vendor firmware so the root cause is unknown: no detection of the unlock on the car?

Could we report this to the vendor ?

**Comment by jerome-benoit** [comment]
Issue reported to vendor.

**Comment by jerome-benoit** [comment]
Moved to asana.
