### ISSUE TITLE
Bug Cahors with badge authentication

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1687]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/d646d42c-d999-43ec-a8c1-d0d31d3a4ab2)

https://slf.evse.cfapps.eu10.hana.ondemand.com/users#inerror

**Comment by jerome-benoit** [comment]
No reproduction pattern.

**Comment by jerome-benoit** [comment]
Version 3.3.2 deployed. Need to check is the issue still occurs.

**Comment by jerome-benoit** [comment]
Moved to asana.
