### ISSUE TITLE
Bug on create a user on tenant which has already an existing user (same email)

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1697]
« An unexpected error occurred »

**Comment by fcoutellier** [comment]
@LucasBrazi06 Leave the test in my hand, we need you on more valuable tasks ;-)

**Comment by jerome-benoit** [comment]
> @fcoutellier
> I tested creation of Tenant + activation email + change password + login in super tenant.
> I tested also registration of new user + activate account + login.
> I tested account locked, suspended, inactive and Pending handling in UI.
> I tested reset password when account is locked -> change password -> user account got unlocked and user can login right away.

But you have not tested the only relevant case here: user is created by an admin in the dashboard and the login by the user after: tested before the PR and it works.

**Comment by fcoutellier** [comment]
@jerome-benoit : I tested it on QA billing tenant. It works fine
