### ISSUE TITLE
Charging Station graph selection automatically unselect Max Grid Limit

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1703]
![2020-06-11_15-45-50](https://user-images.githubusercontent.com/7858535/84482054-5ee00400-ac97-11ea-829f-819e4a3d86b9.gif)

**Comment by LucasBrazi06** [comment]
@fcoutellier I already reported this issue to @OliveGerste 
To be check if there is a dup.

**Comment by fcoutellier** [comment]
@OliveGerste feel free to close this issue if duplicated.

**Comment by OliveGerste** [comment]
@fcoutellier Maybe I missed it, but I do not find an issue for that. So will just leave it open.
