### ISSUE TITLE
Update label: "Load all consumption values (without optimization)" to "Show full chart resolution (1 point per minute)"

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1704]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/9b555f08-81c1-416d-bafd-eb2a093b4f2a)

**Comment by LucasBrazi06** [comment]
Fixed in commit ac003115d79b5e0e693bbc7dd10c62c5ed20c6b6
