### ISSUE TITLE
User > Profile: Delete badge does not work in user's profile

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1711]

**Comment by LucasBrazi06** [comment]
Fixed in commit 6ef34076705bc7da8d38a09e9adbdac42c609f72

**Comment by fcoutellier** [comment]
@LucasBrazi06 Tested on QA Charging Station Tenant. From an inactive user, I can delete a badge but I cannot Save it (inactive "Save" button).

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 Tested on QA Charging Station Tenant. From an inactive user, I can delete a badge but I cannot Save it (inactive "Save" button).

@fcoutellier  What do you mean by 'inactive user'?
