### ISSUE TITLE
Charging Station > Connector: User name is not hidden for Demo role

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1715]

**Comment by LucasBrazi06** [comment]
Fixed in commit LucasBrazi06/ev-server@ad3ba231fbbf59d00395b0e708adcce47d721330

**Comment by fcoutellier** [comment]
@LucasBrazi06 is this URL relevant to test the fix? https://slf.evse.cfapps.eu10.hana.ondemand.com/transactions#history

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 is this URL relevant to test the fix? https://slf.evse.cfapps.eu10.hana.ondemand.com/transactions#history

No it's in the charging station's list / connector details with demo user ;-)
