### ISSUE TITLE
Charging Station > Edit: Update does not work for those not in template

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1716]

**Comment by LucasBrazi06** [comment]
Fixed in commit LucasBrazi06/ev-server@b76ca6d72582aa8cb5d0f51258819f383e1df48f

**Comment by fcoutellier** [comment]
@LucasBrazi06 Tested on QA Tenant Charging Station.
By testing on "CAHORS-01" > changing the Max Power (Watts) > the new value did not enable the "Save" button.

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 Tested on QA Tenant Charging Station.
> By testing on "CAHORS-01" > changing the Max Power (Watts) > the new value did not enable the "Save" button.

That's normal, in charging plan you have an Apply button ;-)
