### ISSUE TITLE
Validate and push the German translation

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1722]

**Comment by jerome-benoit** [comment]
@mariansalceda : just fellow the same work you've done on the spanish translation  integration + the fixes I've made to make it work.

**Comment by jerome-benoit** [comment]
To add a translation in ev-server, you need to: 

- [ ] translate the main json file; 
- [ ] translate de mail notification messages;
- [ ] translate the EULA;  
- [ ] integrate the new locale in the code.

**Comment by LucasBrazi06** [comment]
@fcoutellier german to be tested as well as spanish in all platform (mobile, backend and front-end) - Thanks!

**Comment by mariansalceda** [comment]
I tested the German version and I think it's good. there are some English words/phrases in there and I changed most of them but I can't vouch for my German translation skills. Maybe someone should double check

**Comment by jerome-benoit** [comment]
> I tested the German version and I think it's good. there are some English words/phrases in there and I changed most of them but I can't vouch for my German translation skills. Maybe someone should double check

You tested it on dashboard, server and mobile app? 

You can do PRs for the fixes you've done. If something is wrong, that's not a big deal, we will ask German people to check it anyway.

**Comment by mariansalceda** [comment]
oh , I only tested the mobile app. i'll test the other ones now :)

**Comment by fcoutellier** [comment]
@OliveGerste : Could you please perform a review of the German translation in context?

**Comment by OliveGerste** [comment]
@fcoutellier I think I can do it next week. 
Let us talk about it in the sync meeting on Monday
