### ISSUE TITLE
TypeScript - Disable check rule to avoid to many warning/error raised.

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1730]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/f7675c26-c4be-42d9-928e-6295bf00db83)

**Comment by LucasBrazi06** [comment]
@fcoutellier it's more enable this rule and fix everywhere and in the meantime it will be disable by @jerome-benoit .

**Comment by LucasBrazi06** [comment]
Tested ok
