### ISSUE TITLE
PDF storage

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1754]

**Comment by fcoutellier** [comment]
@LucasBrazi06 : I am not sure how to validate this one. I don't see any PDF   in the Billing QA tenant.

**Comment by fcoutellier** [comment]
Will be tested whe the download feature will be implemented in the UI.
A unit test has been requested accordingly.

**Comment by LucasBrazi06** [comment]
> Will be tested whe the download feature will be implemented in the UI.
> A unit test has been requested accordingly.

Ca tombe bien, il a été implémenté :)

**Comment by fcoutellier** [comment]
Tu me montreras durant notre sync.

**Comment by fcoutellier** [comment]
J'ai trouvé !! ^^
