### ISSUE TITLE
Template: allow to use wildcard in firmware version definition

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-dashboard#1756]

**Comment by LucasBrazi06** [comment]
It could be a regular expression.

**Comment by jerome-benoit** [comment]
> It could be a regular expression.

Allowing regular expression in perfect.

**Comment by jerome-benoit** [comment]
Done in https://github.com/LucasBrazi06/ev-server/commit/fb3865fa853b6f8f4d0c22fbdcc631a399170fae

**Comment by jerome-benoit** [comment]
The capabilities on the Legrand chargers have disappear from the DB since the use of regexp in template.

**Comment by jerome-benoit** [comment]
All related issues fixed. Working fine.
