### ISSUE TITLE
Car Management - Validate converter fix work as expected

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1776]
This issue is related to the issue: https://github.com/LucasBrazi06/ev-server/issues/1643

It will then be necessary to ask Florian to verify when creating a few vehicles if the converter matches properly the one in the cars (check with some old cars such as F. Ozon's one or recent ones like Hanno's and ask them directly).

If we have a problem, we will add new fields to enter the power of the converter installed if different from that proposed by EV-Database (phases nbr amps with power display).

**Comment by LucasBrazi06** [comment]
Done and dups of a task in QA
