### ISSUE TITLE
Charger not in template does not have its global information updated after connectors configuration

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-dashboard#1787]

**Comment by LucasBrazi06** [comment]
Done in commit ce163e4b7d27b591cb37cbd2d3f31517bc77373f

**Comment by fcoutellier** [comment]
@jerome-benoit Hi Jerome, Could you please tell me how we could test this item?

**Comment by jerome-benoit** [comment]
> @jerome-benoit Hi Jerome, Could you please tell me how we could test this item?

You have to use ev-simulator to simulate stations not in template. I think the testperf on QA tenant have such simulated stations: https://testperf.qa-evse.cfapps.eu10.hana.ondemand.com/
