### ISSUE TITLE
Charging Plans List

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1798]
List of Charging Plans (New tab before "In Error" tab)

Columns
- [ ]  Charging Plan name
- [ ]  Charging station ID
- [ ]  Connector ID
- [ ]  Current connector limitation (kW/A)
- [ ]  Site area name (if component Organization is active)
- [ ]  Current site area limitation (W/A)

Details
- [ ] Show the Charging Plan List/Chart component
- [ ]  Add new button "Edit Site Area"
- [ ]  If Smart Charging is active:
   - [ ]  Remove static limitation tab if Smart Charging is active
   - [ ]  Charging Plan:
      - [ ]  Show the current Charging Plan List/Chart component with switch button (chart is displayed by default)
      - [ ]  Hide input fields: Temporary plan, Start date, Apply and Delete buttons
      - [ ]  Auto-refresh on list
   - [ ]  Charging plan should be given a name
   - [ ]  Add field to display the next time the optimizer batch will be triggered or timer (eg. Next Smart Charging will run in … mins).
- [ ]  If Smart Charging is NOT active:
   - [ ]  Name of the charging plan
   - [ ]  Auto-refresh on list and on charging plans drop down

**Comment by LucasBrazi06** [comment]
Dups of #939
