### ISSUE TITLE
Dislplay addition fields for car catalogs in Car create/update modal

### ISSUE THREAD

**Issue by mahdibenromdhane** [LucasBrazi06/ev-dashboard#1808]

**Comment by fcoutellier** [comment]
@mahdibenromdhane Could you please provide me the details that have been added?

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane Could you please provide me the details that have been added?
We added three fields:
- Power
- Ac Power
- Real Range 
![image](https://user-images.githubusercontent.com/33232018/87050897-2b918600-c1ff-11ea-92bc-66b73fd7efeb.png)

**Comment by fcoutellier** [comment]
@mahdibenromdhane : Super thanks!

Why is the list loading that long?
![image](https://user-images.githubusercontent.com/7858535/87054760-cab87c80-c203-11ea-9945-88787ca3fcd7.png)

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane : Super thanks!
> 
> Why is the list loading that long?
> ![image](https://user-images.githubusercontent.com/7858535/87054760-cab87c80-c203-11ea-9945-88787ca3fcd7.png)

I can't reproduce it 
![image](https://user-images.githubusercontent.com/33232018/87057413-1d476800-c207-11ea-9942-746dc4d84da5.png)
are you testing on prod ?

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane Add a flag to not retrieve the images for the pop-up, this is the download which takes time.

**Comment by fcoutellier** [comment]
@mahdibenromdhane : https://testcharger.qa-evse.cfapps.eu10.hana.ondemand.com/car#cars

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane Add a flag to not retrieve the images for the pop-up, this is the download which takes time.

So we don't display the image in the popup anymore ? or do we do a second call the the server once we chose a car catalog ?

**Comment by fcoutellier** [comment]
Not sure to understand your point. In the "Assign Car" popup I don't see any images whereas they seem to be loaded in background. From my understanding, we are waiting a pretty long time to get the list displayed due to the images, but we don't see the images at all :-)

**Comment by LucasBrazi06** [comment]
Yes ! There's no image in the pop-up!

**Comment by mariansalceda** [comment]
@fcoutellier Validated  with no issues
