### ISSUE TITLE
Meter value problems

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1817]
Could you please have a look at this?
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/0c51455a-64df-4525-b4ba-a94835add4a3)

**Comment by LucasBrazi06** [comment]
Jul 9, 2020, 2:09:54 PM - Gerald SEILER > Connector '1' > Transaction ID '795105678' > Instant: 21.13 kW, Total: 5.15 kW.h
[
      {
            "payload": {
                  "connectorId": 1,
                  "transactionId": 0,
                  "meterValue": [
                        {
                              "timestamp": "2020-07-09T12:09:11.940Z",
                              "sampledValue": [
                                    {
                                          "value": "5.146",
                                          "context": "Sample.Periodic",
                                          "format": "Raw",
                                          "measurand": "Energy.Active.Import.Register",
                                          "unit": "kWh"
                                    },
                                    {
                                          "value": "222.5",
                                          "context": "Sample.Periodic",
                                          "format": "Raw",
                                          "measurand": "Voltage",
                                          "unit": "V"
                                    },
                                    {
                                          "value": "32.09",
                                          "context": "Sample.Periodic",
                                          "format": "Raw",
                                          "measurand": "Current.Export",
                                          "unit": "A"
                                    }
                              ]
                        }
                  ]
            }
      }
]
5.146 - 4.970 * (3600 / 30) = 21 120W

Jul 9, 2020, 2:08:24 PM - Gerald SEILER > Connector '1' > Transaction ID '795105678' > Instant: 4.29 kW, Total: 4.97 kW.h
[
      {
            "payload": {
                  "connectorId": 1,
                  "transactionId": 0,
                  "meterValue": [
                        {
                              "timestamp": "2020-07-09T12:08:41.959Z",
                              "sampledValue": [
                                    {
                                          "value": "4.970",
                                          "context": "Sample.Periodic",
                                          "format": "Raw",
                                          "measurand": "Energy.Active.Import.Register",
                                          "unit": "kWh"
                                    },
                                    {
                                          "value": "224.0",
                                          "context": "Sample.Periodic",
                                          "format": "Raw",
                                          "measurand": "Voltage",
                                          "unit": "V"
                                    },
                                    {
                                          "value": "32.04",
                                          "context": "Sample.Periodic",
                                          "format": "Raw",
                                          "measurand": "Current.Export",
                                          "unit": "A"
                                    }
                              ]
                        }
                  ]
            }
      }
]

Jul 9, 2020, 2:06:54 PM - Gerald SEILER > Connector '1' > Transaction ID '795105678' > Instant: 21.26 kW, Total: 4.79 kW.h
[
      {
            "payload": {
                  "connectorId": 1,
                  "transactionId": 0,
                  "meterValue": [
                        {
                              "timestamp": "2020-07-09T12:06:11.919Z",
                              "sampledValue": [
                                    {
                                          "value": "4.791",
                                          "context": "Sample.Periodic",
                                          "format": "Raw",
                                          "measurand": "Energy.Active.Import.Register",
                                          "unit": "kWh"
                                    },
                                    {
                                          "value": "224.5",
                                          "context": "Sample.Periodic",
                                          "format": "Raw",
                                          "measurand": "Voltage",
                                          "unit": "V"
                                    },
                                    {
                                          "value": "32.09",
                                          "context": "Sample.Periodic",
                                          "format": "Raw",
                                          "measurand": "Current.Export",
                                          "unit": "A"
                                    }
                              ]
                        }
                  ]
            }
      }
]

Jul 9, 2020, 2:05:22 PM - Gerald SEILER > Connector '1' > Transaction ID '795105678' > Instant: 4.27 kW, Total: 4.61 kW.h
[
      {
            "payload": {
                  "connectorId": 1,
                  "transactionId": 0,
                  "meterValue": [
                        {
                              "timestamp": "2020-07-09T12:05:41.943Z",
                              "sampledValue": [
                                    {
                                          "value": "4.614",
                                          "context": "Sample.Periodic",
                                          "format": "Raw",
                                          "measurand": "Energy.Active.Import.Register",
                                          "unit": "kWh"
                                    },
                                    {
                                          "value": "223.6",
                                          "context": "Sample.Periodic",
                                          "format": "Raw",
                                          "measurand": "Voltage",
                                          "unit": "V"
                                    },
                                    {
                                          "value": "31.92",
                                          "context": "Sample.Periodic",
                                          "format": "Raw",
                                          "measurand": "Current.Export",
                                          "unit": "A"
                                    }
                              ]
                        }
                  ]
            }
      }
]

**Comment by jerome-benoit** [comment]
It's not a production charger, it's the charger Gerald test in the lab. 
So i will not say that it's a high prio issue ;)

**Comment by LucasBrazi06** [comment]
> It's not a production charger, it's the charger Gerald test in the lab.
> So i will not say that it's a high prio issue ;)

Double check with him :-)
It's a potential low-cost Wallbox for our colleagues @ home...

**Comment by jerome-benoit** [comment]
> > It's not a production charger, it's the charger Gerald test in the lab.
> > So i will not say that it's a high prio issue ;)
> 
> Double check with him :-)
> It's a potential low-cost Wallbox for our colleagues @ home...

The vendor support is already taking care of the issue.

**Comment by fcoutellier** [comment]
@jerome-benoit : Perfect then, please just do the follow-up :-)

**Comment by jerome-benoit** [comment]
> @jerome-benoit : Perfect then, please just do the follow-up :-)

Ask Gerald to do it, I do not follow that issue ;)

**Comment by fcoutellier** [comment]
Jerome mailed the vendor to ask them to test directly.

**Comment by jerome-benoit** [comment]
Moved to Asana.
