### ISSUE TITLE
evses.connectors.tariff_id -> Add simple pricing

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1824]

**Comment by jerome-benoit** [comment]
That one is a full OCPI module implementation called Tariff. Even the bare minimum will require more than a dev day.

**Comment by fcoutellier** [comment]
@jerome-benoit : Ok, I'll schedule a meeting so that we can have a common understanding of what need to be done.

**Comment by jerome-benoit** [comment]
I currently add the OCPI Tariff endpoint(s) to the ev-server CPO REST API to export the simple pricing settings properly remapped and the corresponding id added to OCPI connectors in OCPI locations. 
I do not think that it will be finished today (means implemented and fully tested with Postman).

**Comment by jerome-benoit** [comment]
- [ ] Simple pricing: 
    - add a time base to the pricing rates
    - add connector power criterion to the pricing rates (OCPI wants amperage per phase in the end)
    - add date and time to pricing rates  
    - add pricing settings historic 
    - add inactivity penalty 
- [ ] CPO: 
    - [ ] GET Tariffs endpoint
    - [ ] push Tariffs
- [ ] eMSP: 
    - [ ] push/pull Tariffs 
    - [ ] Tariffs endpoints
- [ ] Get the OCPI module Tariffs certified by Gireve
