### ISSUE TITLE
Transaction History - New table button to 'Navigate To Charge Plan'

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1849]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/7e80a1fa-cf29-40f6-8c1a-1d6f67c945ce)

**Comment by LucasBrazi06** [comment]
Maybe not possible as charging plan is applied for the transaction only when Smart Charging is active and is deleted just after.

**Comment by LucasBrazi06** [comment]
Jump to charging plans with filtering on Charging Station ID + Connector ID

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane could you provide also this table action to the Session In Progress list?
Thanks.

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane could you provide also this table action to the Session In Progress list?
> Thanks.

Done :)

**Comment by LucasBrazi06** [comment]
> > @mahdibenromdhane could you provide also this table action to the Session In Progress list?
> > Thanks.
> 
> Done :)

Thanks!
PR?

**Comment by mahdibenromdhane** [comment]
> > > @mahdibenromdhane could you provide also this table action to the Session In Progress list?
> > > Thanks.
> > 
> > 
> > Done :)
> 
> Thanks!
> PR?
I have connected to a wrong issue, now it's good
https://github.com/LucasBrazi06/ev-dashboard/pull/2047

**Comment by WillyLellouch** [comment]
Tested with multiple combinations of charging plans and sessions. Works as intended, closing issue
