### ISSUE TITLE
Performance issue filter

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1855]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/462630d9-a82f-469c-ba30-1d124f5a9450)

**Comment by LucasBrazi06** [comment]
It's a generic filter not linked to the content of the list.

**Comment by fcoutellier** [comment]
Ok, let keep this in icebox for a potential replacement ff the generic control later on.
