### ISSUE TITLE
Log - Enable the Charging Station filter in addtion to the "Smart Charging" filter

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1856]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/54a38575-6ba4-4892-ba2e-7db07712fcd5)

**Comment by LucasBrazi06** [comment]
The charging station filters only the Source column

**Comment by fcoutellier** [comment]
Correct but here Smart Charging source is always "Central Server" which is not helpful if you work on a specific charging station. Could we specify the charging station ID instead of "Central Server" which has no value in fact?

**Comment by LucasBrazi06** [comment]
Smart Charging work at Site Area level.

**Comment by LucasBrazi06** [comment]
As discussed we cannot filter inside the detailed area in MongoDB
