### ISSUE TITLE
Tenant : Add address + Logo in Tenant management

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1864]
- [ ] Add address + GPS coordinates
- [ ] Add logo
- [ ] Add endpoint to retrieve the logo (not protected - for login page)

Tips: this is similar to Company

**Comment by fcoutellier** [comment]
@mahdibenromdhane : Could you please take care of this?

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane : Could you please take care of this?

okey

**Comment by LucasBrazi06** [comment]
As you are at school, I'll make the necessary changes.
