### ISSUE TITLE
Billing - Unit Test

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1865]
- [ ] Connection test to Stripe
   - [ ]   Public key incorrect
   - [ ]   Private Key incorrect
   - [ ]   URL incorrect
- [ ] Trigger charging session without Stripe connection
- [ ] Trigger billing with charging session in error
- [ ] Get PDF from Stripe
- [ ] Prevent deletion when linked to an invoice

Feel free to add any other missing tests

**Comment by mariansalceda** [comment]
@Ninjeneer  already fixed it in the issue #1864  PR#1718  and is waiting for the review.

**Comment by fcoutellier** [comment]
Duplicated and already done by Loan.
