### ISSUE TITLE
Charging Station - Exclude from Smart Charging

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1869]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/7f33644e-d21e-4885-bb39-4172f3b2d25d)
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/87f10f44-71a5-4da0-90ff-edafcc52eb20)

**Comment by jerome-benoit** [comment]
THe static limitation and the charging profiles are two differents features. And can be used independently. 

THe issue here was just the misleading red message?

**Comment by LucasBrazi06** [comment]
> The static limitation and the charging profiles are two differents features. And can be used independently.
> 
> The issue here was just the misleading red message?

When you exclude the charging station from the Smart Charging, you can play with it with the Static Limitation and Charging Profile, so these features should be active.
The power of the charging station is deduced from the total power of the site area.

**Comment by jerome-benoit** [comment]
Tested on QA, work as expected.
