### ISSUE TITLE
Add a new field Amps per phase in Edit Charging Station

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1903]
Charging station matches the template:
- [x] Add a new r/o field in edit charging station to display the amps per phase
Charging station IS NOT matching the template:
- [x] Amp per phase should be editable by the user and Total Amps updated accordingly
- [x] The total amps is sent to the backend as before

**Comment by jerome-benoit** [comment]
QA: For charging stations not in template, it's working as expected with mono and tri phased settings.
