### ISSUE TITLE
Security: provide the list of open sources used by ev-server, ev-dashboard and ev-mobile

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1907]
Write a list in an Excel document with the following information
- 1 Name of the open source
- 2 Version
- 3 License name (MIT, Apache...) in GitHub repo

The two first one can be found in the package.json in 'dependencies'section and the last one n the repository of the open source's github.

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/b0914bcb-d990-4080-b239-a35f637c5660)

This has to be done for the 3 repositories (1 Excel tab per repo).

Send me the Excel document once done.

**Comment by jerome-benoit** [comment]
After the first manual creation of the excel file, investigating on how to automate it might worth it: 

+ https://medium.com/@fokusman/the-easiest-way-to-check-all-your-npm-dependency-licenses-753075ef1d9d 
+ https://github.com/franciscop/legally
+ etc.

**Comment by mariansalceda** [comment]
I did it as @jerome-benoit  said and it as some extra nformation. I can remove it if necessary. 

[sources.xlsx](https://github.com/LucasBrazi06/ev-dashboard/files/5050674/sources.xlsx)

**Comment by LucasBrazi06** [comment]
Done
