### ISSUE TITLE
No more selection box in Refunding screen

### ISSUE THREAD

**Issue by yannpub** [LucasBrazi06/ev-dashboard#1914]
_Version:_ 2.3.29

_Issue:_ There is no more tick box available in the refunding screen. Therefore it is impossible to select sessions and ask for refund.

**Comment by LucasBrazi06** [comment]
You were not Site Owner, I just added you and you should have your selection checkbox column

![image](https://user-images.githubusercontent.com/25266945/90607389-6ecd1480-e201-11ea-836d-e574c6ae803f.png)
