### ISSUE TITLE
Add edit charging station edit filed

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1920]
This is already possible over the OCCP parameters tab => param: 'boxidentity' but not that much user-friendly.

![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/2ca3eea5-e424-48a9-b715-eb3b9df81891)

Requested by customer who want to change their Charging Station naming convention but did not find how to do it.

**Comment by WillyLellouch** [comment]
Do you want a new field in this screen then ?

**Comment by fcoutellier** [comment]
Yes a new text field please.

**Comment by jerome-benoit** [comment]
You can’t just change the name of a charging station in the DB:

* You have to identify the OCPP parameter that permit to set the chargebox id and it’s vendor dependent;
* You have to integrate that in the template handling code and amend all templates;
* You have to extend the vendor specific classes;
* You then can add the code to properly set the charging station name by using the right OCPP key.

Having two different names not in sync for the same asset is not maintainable.

So in the meantime, the customer have to change the charging station name on the firmware admin interface.

**Comment by LucasBrazi06** [comment]
The charging station ID is set in the admin console at the time you connect it to the backend.

**Comment by jerome-benoit** [comment]
> 
> Closed #1920 <https://github.com/LucasBrazi06/ev-dashboard/issues/1920>.
> 
> 

It’s a valid end-user usability feature request issue that is possible to implement.
What is the point of closing such issues without giving any reason?
They can stay open with a low prio and users can upvote and downvote features request so their importance can be properly evaluated with a user centric approach.

Globally, closing doable feature request issue is just one of the “don’t” at issues management on open source project. It’s brutal, especially if that’s a doable feature request that is done by a end-user and if that’s done without a very detailed explanation.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3
