### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1933]
Here is the Portuguese translation to integrate
[https://app.zenhub.com/files/141851541/3e326e2e-929a-4fcf-8d4e-4c59bc6302ec/download](https://app.zenhub.com/files/141851541/3e326e2e-929a-4fcf-8d4e-4c59bc6302ec/download)

**Comment by LucasBrazi06** [comment]
Wait Cesar !
