### ISSUE TITLE
Angular Training

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1939]

**Comment by Jakob8** [comment]
@fcoutellier 
Where can I find the link to the course?

**Comment by fcoutellier** [comment]
@LucasBrazi06 : Could you provide the link to the training material please?

**Comment by LucasBrazi06** [comment]
@fcoutellier It's in the onboarding document in sharepoint

**Comment by fcoutellier** [comment]
@Jakob8 please see: https://sap.sharepoint.com/:p:/r/sites/108195/Shared%20Documents/Development%20Environment/Charge-Angels%20-%20Onboarding%20Guide.pptx?d=w6558170687154ec781142707afb58622&csf=1&web=1&e=3L9nwl
