### ISSUE TITLE
Get access to Hubject system

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1943]

**Comment by Jakob8** [comment]
- CSR and the IP addresses submitted

- As soon as the certificates are signed and the IP addresses are whitelisted, Hubject will configure the partner account for the HBS QA environment. (This takes appr. 3 working days)

- With the access details we are able to proceed with phase 2 "QA environment, implementation and testing"

**Comment by Jakob8** [comment]
Message from Hubject Sep. 15.
"Hey Jakob,

I have sent the CSR for signing. 
Hopefully it gets signed without any issues.

I will let you know."
