### ISSUE TITLE
Billing: Fix Billing Unit Tests

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1945]

**Comment by LucasBrazi06** [comment]
I still have issues:
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/903a6aaf-f5b6-4772-bc2e-67c8979560b6)

**Comment by Ninjeneer** [comment]
I don't think that setting a timeout for those tests is relevant, as Stripe synchronization (users + invoices) may take way more than 30 seconds. Is there a way to disable Axios timeout for a specific request, or should I add it ?

**Comment by LucasBrazi06** [comment]
Ok
