### ISSUE TITLE
Notification management no longer available for basic user (Tab is missing)

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1963]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/3a4e123d-7b38-4ef0-ad9c-56277a338494)

**Comment by fcoutellier** [comment]
Hi Mahdi, it would be great if you could handle this ASAP since customers will use it very soon. Thanks, Fred

**Comment by mahdibenromdhane** [comment]
> Hi Mahdi, it would be great if you could handle this ASAP since customers will use it very soon. Thanks, Fred

Okey

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane Have you checked that the Basic user can change its notification options and we take it into account in the backend?
Seems that only the Admin could do that before.
Let me know.
Thanks!

**Comment by OliveGerste** [comment]
Notification tab is available again for admin- and basic user. The settings are saved from the backend, when changes are made.

**Comment by LucasBrazi06** [comment]
You can close the issue next time if it's ok ;-)
