### ISSUE TITLE
Migration task on badges

### ISSUE THREAD

**Issue by mahdibenromdhane** [LucasBrazi06/ev-dashboard#1974]
Migration 
  - [ ] Set all the tags props 'issuer' aligned with users (select user with issuer = true + update all their issuer tags to true)
  - [ ] Align changed/created by/on of tag with user also
  - [ ] If no description is provided, provide the following: `Tag ID '${tag.id}'`
  - [ ] Set all ANONYMIZED user tags to ANONYMIZED tags

**Comment by LucasBrazi06** [comment]
ok
