### ISSUE TITLE
Cars > Bug on detect changes 

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1977]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/b86f3862-87ad-455c-accc-533342c1183e)
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/53a3e27a-769c-4923-890c-2fda5253d351)

How-To-Reproduce:

1. Open SLF
Click on Organization => Site Area.
Edit the first entry and click the cross to close the popup => no changes detected
Repeat the same with the second entry => a change is detected whereas there is not

**Comment by mahdibenromdhane** [comment]
Not reproducible anymore.
