### ISSUE TITLE
Sessions > Logs: Jump to logs with Session ID is not fast

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#2041]
Jump from Session ID here:

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/da5c46a3-3d73-4cf9-aadf-79ff44376829)

Should be replace by: Start transaction timestamp + charging station ID + log level to info + ordered log timestamp asc:

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/024f09f9-d5f1-435e-b3f8-ac4c8a3f8f5a)

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane 
I removed the Search in the query string.
Do the same jump in Session In Error and History if not done in another PR

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane
I meant not History but In Progress also ;-)

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane
> I meant not History but In Progress also ;-)

okey

**Comment by stefania-santimbrean** [comment]
Tested and it looks like in the requirement screenshots.
