### ISSUE TITLE
Table Action > Check: Rename Check to NavigateTo everywhere

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#2044]
TableCheckLogsAction -> TableNavigateToLogsAction
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/c61b0174-af74-4ae3-ab89-e75665e36527)

CHECK_LOGS = 'check_logs' -> NAVIGATE_TO_LOGS = 'navigate_to_logs',
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/e20483dd-db1d-40d9-9c2d-5992482349bd)

For all same kind of actions

**Comment by WillyLellouch** [comment]
Made a small fix for a forgotten
See #2202

**Comment by WillyLellouch** [comment]
Rechecked the naming for all instances of this type of action, found all of them to be conform.
Closing Issue.
