### ISSUE TITLE
Charging Station: Provide QR Code per connector

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#2068]
Goal is to display a QR-Code in a new tab in the Charging Station pop-up per connector.
You can schedule me a meeting

**Comment by LucasBrazi06** [comment]
Also add a preview of a connector's QR-Code in a pop-up

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane I refactored the QR-Code, double check my changes, learn, test it and let me know if I can merge it.
Thanks.

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane I refactored the QR-Code, double check my changes, learn, test it and let me know if I can merge it.
> Thanks.

Ok :)

**Comment by stefania-santimbrean** [comment]
Test functionality and it works:
- in the Charging Stations tab, generating the QR code works -  downloads a pdf with the QR codes.
- in the Charing Stations tab, press Edit on a Charging Station which has status connected and press on Generate QR code - pop up appears with QR code for that connector. Download button works there also.

**Comment by LucasBrazi06** [comment]
@stefania-santimbrean You can close the issue if it works, thanks!
