### ISSUE TITLE
Navigation: Jump from User to Tags or vice versa should take into account Org filtering

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#2070]
When you navigate from User list to Tag list, you must pass the organization all the time (you can check on SLF).
Check also other navigations.

**Comment by WillyLellouch** [comment]
When using the row action to jump to a corresponding user, tag, or session, the filter corresponds to the org to which the original item belonged.
I think this is correct however the issue title suggest that it should instead take the original **filter** into account not the item from which the jump is made. 
Could I have a clarification on that ?

**Comment by LucasBrazi06** [comment]
@WillyLellouch For instance if you jump to the Tag list with an external tag, filters should be set too External Org + Tag ID in the search field.

**Comment by WillyLellouch** [comment]
@LucasBrazi06 Okay then everything is working as intended ;)
Closing issue
