### ISSUE TITLE
Unit Tests: OCPP Tests are not re-entrant

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#2122]
Run createContext and execute twice the OCPP tests: 'npm run mochatest:ocpp'
The first run passes and the second fails.
These tests must be re-entrant.
Could you please have a look?
Thanks!

**Comment by mahdibenromdhane** [comment]
> Run createContext and execute twice the OCPP tests: 'npm run mochatest:ocpp'
> The first run passes and the second fails.
> These tests must be re-entrant.
> Could you please have a look?
> Thanks!

Ok.

**Comment by OliveGerste** [comment]
Tested - OCPP Tests are re-entrant again.
