### ISSUE TITLE
Badge list: Add Status filter + Delete of Badges with multi-selection

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#2124]
Requested by our customer

**Comment by WillyLellouch** [comment]
@LucasBrazi06 Status filter works as intended, multi delete works as well, whether activated or not, default or not, filters correctly limits selection of tickboxes and if there are tags associated with sessions, the ones that are not are deleted and an error logged for the rest.
No issues on my end.

**Comment by LucasBrazi06** [comment]
Thanks Willy!
