### ISSUE TITLE
docker build - central server not found

### ISSUE THREAD

**Issue by fb2010** [LucasBrazi06/ev-dashboard#2147]
When building/deploying central server and dashboard in docker (with defautl settings) I am having trouble logging in to the dashboard.

All the builds are done with "make SUBMODULES_INIT=false" (both for server and dashboard). Build finishes without errors, and I can see docker images populating right ports, but when I try to login to dashboard it throws and error that it can not connect to backend server.

Are there any additional setting that should be set?

**Comment by jerome-benoit** [comment]
Everything is working flawlessly after building ev-dashboard and ev-server docker images. 

You can't use ev-server docker env and ev-dashboard not as a docker image if you do not know how to configure docker properly. 

The e-mobility dev env recommended setup is to do it bare metal anyway.

**Comment by JRGONGk** [comment]
> When building/deploying central server and dashboard in docker (with defautl settings) I am having trouble logging in to the dashboard.
> 
> All the builds are done with "make SUBMODULES_INIT=false" (both for server and dashboard). Build finishes without errors, and I can see docker images populating right ports, but when I try to login to dashboard it throws and error that it can not connect to backend server.
> 
> Are there any additional setting that should be set?

Hi have you solved the error?

**Comment by jerome-benoit** [comment]
Cannot reproduce.
