### ISSUE TITLE
Failed to Login/Register

### ISSUE THREAD

**Issue by JRGONGk** [LucasBrazi06/ev-dashboard#2150]
Whenever I enter the superadmin credentials(which i have defined in test/config/local.json) in the login page. It shows error "WRONG EMAIL ID or PASSWORD"  and also when I do registration of a new user , when I click to register it gives no response.

Here, is my local.json configuration for superadmin/admin 
  "superadmin": {
    "username": "super.admin@sap.com",
    "password": "Kartik@321"
  },
  "admin": {
    "username": "admin@sap.com",
    "password": "Kartik@321"
  },

Here, is my config file for ev-server:

   "CentralSystemRestService": {
    "protocol": "http",
    "host": "107.191.44.218",
    "port": 80,
    "userTokenKey": "YourSecureKeyToEncodeTokenAuth",
    "userTokenLifetimeHours": 12,
    "userDemoTokenLifetimeDays": 365,
    "captchaSecretKey": "6LegQQMaAAAAAInu_Jji6OALO-hd_h_2fbQQ7T1O",
    "debug": true
  },
  "CentralSystemFrontEnd": {
    "protocol": "https",
    "host": "localhost",
    "port": 8080
  },

**Comment by jerome-benoit** [comment]
You have to learn to make:

+ fully contextualized issue: what are you trying to do? on which component? ... 
+ not put sensitive information in clear in them, like password;
+ use github code formatting when required to make your inputs readable.

Initial user creation need to be done directly on the DB with tool like robo3T.

**Comment by jerome-benoit** [comment]
> Whenever I enter the superadmin credentials(which i have defined in test/config/local.json) in the login page. It shows error "WRONG EMAIL ID or PASSWORD" and also when I do registration of a new user , when I click to register it gives no response.
>
> Here, is my config file for ev-server:
> 
> ],
> "CentralSystemRestService": {
> "protocol": "http",
> "host": "107.191.44.218",

Use localhost. 

> "port": 80,
> "userTokenKey": "YourSecureKeyToEncodeTokenAuth",
> "userTokenLifetimeHours": 12,
> "userDemoTokenLifetimeDays": 365,
> "captchaSecretKey": "6LegQQMaAAAAAInu_Jji6OALO-hd_h_2fbQQ7T1O",
> "debug": true
> },
> "CentralSystemFrontEnd": {
> "protocol": "https",
> "host": "localhost",
> "port": 8080
> },

I doubt that section match the one the dashboard is using to listen for HTTP request.

**Comment by JRGONGk** [comment]
The dashboard is also listening to port 80.

**Comment by jerome-benoit** [comment]
> The dashboard is also listening to port 80.

Doing a `npm start` make the dashboard listen on localhost:45000 and await for HTTP requests

**Comment by JRGONGk** [comment]
I have done the same configuration you have mentioned, but now it showing "CANT REACH TO THE CENTRAL SERVER".

Dashboard config.json file:

{
  "CentralSystemServer": {
    "protocol": "http",
    "host": "localhost",
    "port": 80
  },
  "FrontEnd": {
    "host": "localhost"
  },
  "Authorization": {
    "debug": false
  },

Server config.json file:

 "CentralSystemRestService": {
    "protocol": "http",
    "host": "localhost",
    "port": 80,
    "userTokenKey": "YourSecureKeyToEncodeTokenAuth",
    "userTokenLifetimeHours": 12,
    "userDemoTokenLifetimeDays": 365,
    "captchaSecretKey": "6LegQQMaAAAAAInu_Jji6OALO-hd_h_2fbQQ7T6O",
    "debug": true
  },

**Comment by JRGONGk** [comment]
I am using ubuntu 18 Linux.

**Comment by jerome-benoit** [comment]
> I am using ubuntu 18 Linux.

I doubt you can listen on port 80 on GNU/Linux distro without root privileges. 
And I doubt you have properly put a user record with the right password properly hashed. 

I think your dev env proper setup can wait for next week.

**Comment by JRGONGk** [comment]
"And I doubt you have properly put a user record with the right password properly hashed." - The user record and password is properly defined in /test/config/local.json.

**Comment by JRGONGk** [comment]
![server](https://user-images.githubusercontent.com/51272647/102013513-acd4e200-3d76-11eb-844e-dffd03024b96.png)
If the server is checking the credentials it means it is connected to the dashboard?

**Comment by fb2010** [comment]
> ![server](https://user-images.githubusercontent.com/51272647/102013513-acd4e200-3d76-11eb-844e-dffd03024b96.png)
> If the server is checking the credentials it means it is connected to the dashboard?

I am strugguling with same problems as you (can not get dashoard connection to server) if I access it from another client (not from server where the dashboard and server are running).

Would you share your config file for server and dahsboard, becasue I can not set it up correctly?

**Comment by jerome-benoit** [comment]
> I am strugguling with same problems as you (can not get dashoard connection to server) if I access it from another client (not from server where the dashboard and server are running).
> 
> Would you share your config file for server and dashboard, because I can not set it up correctly?

If you have access to the project share, you should have access to an archive with default working configurations called ev-config-scripts.zip. 
As well as the matching empty-db.zip archive. 
I think all of it is already documented in the onboarding guide that you should have received. 


> "And I doubt you have properly put a user record with the right password properly hashed." - The user record and password is properly defined in /test/config/local.json.

In the DB I mean.

**Comment by fb2010** [comment]
> If you have access to the project share, you should have access to an archive with default working configurations called ev-config-scripts.zip.

Could find the mentioned item, is it uploaded to the git repo?

**Comment by jerome-benoit** [comment]
> > If you have access to the project share, you should have access to an archive with default working configurations called ev-config-scripts.zip.
> 
> Could not find the mentioned item, is it uploaded to the git repo?

If you have not received the onboarding guide + SAP laptop + the sharepoint access, then you will have to wait a bit and train yourselves on typescript, MongoDB, etc.

**Comment by JRGONGk** [comment]
Here is my server config.json file:

{
  "EVDatabase": {
    "url": "",
    "key": ""
  },
  "Crypto": {
    "key": "",
    "algorithm": ""
  },
  "Cluster": {
    "enabled": false,
    "numWorkers": 2
  },
  "CentralSystems": [
    {
      "type": "ocpp",
      "implementation": "soap",
      "protocol": "http",
      "host": "localhost",
      "port": 8000,
      "debug": false
    },
    {
      "type": "ocpp",
      "implementation": "json",
      "protocol": "wss",
      "host": "localhost",
      "port": 8010,
      "keepaliveinterval": 30,
      "debug": false
    }
  ],
  "CentralSystemRestService": {
    "protocol": "http",
    "host": "localhost",
    "port": 80,
    "userTokenKey": "YourSecureKeyToEncodeTokenAuth",
    "userTokenLifetimeHours": 12,
    "userDemoTokenLifetimeDays": 365,
    "socketIO": true,
    "socketIOListNotificationIntervalSecs": 5,
    "socketIOSingleNotificationIntervalSecs": 1,
    "debug": false
  },
  "CentralSystemFrontEnd": {
    "protocol": "https",
    "host": "localhost",
    "port": 8080,
    "distEnabled": false,
    "distPath": "../dist/front-end"
    
  },
  "OCPIService": {
    "protocol": "https",
    "host": "localhost",
    "port": 9090,
    "ssl-key": "",
    "ssl-cert": "",
    "ssl-ca": [],
    "debug": false,
    "externalProtocol": "https"
  },
  "CentralSystemServer": {
    "protocol": "https",
    "host": "localhost",
    "port": 443
  },
  "ODataService": {
    "protocol": "https",
    "host": "localhost",
    "port": 9090,
    "ssl-key": "",
    "ssl-cert": "",
    "ssl-ca": [],
    "debug": false,
    "externalProtocol": "https"
  },
  "WSDLEndpoint": {
    "baseUrl": ""
  },
  "JsonEndpoint": {
    "baseUrl": ""
  },
  "OCPIEndpoint": {
    "baseUrl": ""
  },
  "Storage": {
    "implementation": "mongodb",
    "host": "localhost",
    "port": 27017,
    "user": "evse-user",
    "password": "123456",
    "schema": "evse",
    "database": "evse",
    "debug": false
  },
  "Notification": {
    "Email": {
      "enabled": true
    },
    "RemotePushNotification": {
      "enabled": true
    }
  },
  "Firebase": {
    "type": "",
    "projectID": "",
    "privateKeyID": "",
    "privateKey": "",
    "clientEmail": "",
    "clientID": "",
    "authURI": "",
    "tokenURI": "",
    "authProviderX509CertURL": "",
    "clientX509CertURL": "",
    "databaseURL": ""
  },
  "Email": {
    "from": "info@vmayo.care",
    "bcc": "",
    "smtp": {
      "host": "rmta.vmayo.care",
      "port": 587,
      "secure": true,
      "requireTLS": false,
      "type": "plain",
      "user": "ev",
      "password": "dBkRx-ixc---6MQkwBQngQN6Nk",
      "debug": false
    },
    "smtpBackup": {
      "from": "",
      "host": "",
      "port": 465,
      "secure": true,
      "requireTLS": false,
      "user": "",
      "password": ""
    }
  },
  "Authorization": {
    "debug": false
  },
    "ChargingStation": {
    "heartbeatIntervalSecs": 60,
    "checkEndOfChargeNotificationAfterMin": 5,
    "notifBeforeEndOfChargePercent": 50,
    "notifBeforeEndOfChargeEnabled": false,
    "notifEndOfChargePercent": 0,
    "notifEndOfChargeEnabled": true,
    "notifStopTransactionAndUnlockConnector": false
  },
  "Locales": {
    "default": "en_US",
    "supported": [
      "en_US",
      "fr_FR",
      "es_MX",
      "de_DE",
      "pt_PT"
    ]
  },
  "Migration": {
    "active": true
  },
  "Scheduler": {
    "active": false,
    "tasks": []

Here is my dashboard config.json file:

{
  "CentralSystemServer": {
    "protocol": "http",
    "host": "localhost",
    "port": 80
  },
  "FrontEnd": {
    "host": "localhost"
  },
  "Authorization": {
    "debug": false
  },
  "Asset": {
    "maxImageKb": 800
  },
  "User": {
    "maxPictureKb": 150,
    "captchaSiteKey": ""
  },
  "Tenant": {
    "maxLogoKb": 150
	},
  "Company": {
    "maxPictureKb": 150
  },
  "Site": {
    "maxPictureKb": 800
  },
  "SiteArea": {
    "maxPictureKb": 800
  },
  "Car": {
    "url": ""
  },
  "Locales": {
    "default": "en",
    "supported": [
      "en",
      "fr",
      "es",
      "de",
      "pt"
    ],
    "fullSupported": [
      "en_US",
      "fr_FR",
      "es_MX",
      "de_DE",
      "pt_PT"
    ]
  },
  "Advanced": {
    "debounceTimeNotifMillis": 50,
    "debounceTimeSearchMillis": 500
  },
  "Debug": {
    "enabled": true
  }
}

Please take a look and tell me the required correction.

**Comment by JRGONGk** [comment]
> > > If you have access to the project share, you should have access to an archive with default working configurations called ev-config-scripts.zip.
> > 
> > 
> > Could not find the mentioned item, is it uploaded to the git repo?
> 
> If you have not received the onboarding guide + SAP laptop + the sharepoint access, then you will have to wait a bit and train yourselves on typescript, MongoDB, etc.

Can you please tell me if I need to do any correction in the config files that I have mentioned above or any files that I need to give permissions from root?

**Comment by JRGONGk** [comment]
> > I am strugguling with same problems as you (can not get dashoard connection to server) if I access it from another client (not from server where the dashboard and server are running).
> > Would you share your config file for server and dashboard, because I can not set it up correctly?
> 
> If you have access to the project share, you should have access to an archive with default working configurations called ev-config-scripts.zip.
> As well as the matching empty-db.zip archive for an initial working DB.
> I think all of it is already documented in the onboarding guide that you should have received.
> 
> > "And I doubt you have properly put a user record with the right password properly hashed." - The user record and password is properly defined in /test/config/local.json.
> 
> In the DB I mean.

In the admin DB I have created a user "evse-admin" with a strong password and another DB "evse" I have created "evse-user" with the same password.

**Comment by JRGONGk** [comment]
> > I am strugguling with same problems as you (can not get dashoard connection to server) if I access it from another client (not from server where the dashboard and server are running).
> > Would you share your config file for server and dashboard, because I can not set it up correctly?
> 
> If you have access to the project share, you should have access to an archive with default working configurations called ev-config-scripts.zip.
> As well as the matching empty-db.zip archive for an initial working DB.
> I think all of it is already documented in the onboarding guide that you should have received.
> 
> > "And I doubt you have properly put a user record with the right password properly hashed." - The user record and password is properly defined in /test/config/local.json.
> 
> In the DB I mean.

Can you please tell the path of ev-config-scripts.zip and empty-db.zip

**Comment by JRGONGk** [comment]
![2020-12-14](https://user-images.githubusercontent.com/51272647/102041968-bb62de00-3df6-11eb-8567-5de7b9e2a306.png)
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
which path here it is talking about, I am surely missing concept here but can you please help

**Comment by jerome-benoit** [comment]
Could please just read and follow the sentence already written: 

'If you have not received the onboarding guide + SAP laptop + the sharepoint access, then you will have to wait a bit and train yourselves on typescript, MongoDB, etc.'? 

That will avoid to fill that issue uselessly. Eveything will resolve by itself once you have received the onboarding guide and follow the required trainings.

**Comment by JRGONGk** [comment]
Okay Thanks I will follow the instructions.
