### ISSUE TITLE
Charging Station: Actions should be disabled on disconnected charging stations

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#2173]
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/9d1571eb-8b18-4bf1-9a49-61992a09fdcf)

**Comment by WillyLellouch** [comment]
@LucasBrazi06 This is working as intended before and after the Station is connected, so good on my end.

**Comment by LucasBrazi06** [comment]
Thanks!
Feel free to close the issue yourself ;-)
